# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        exclude: '^(requirements.txt|requirements-dev.txt)$'
      # Unify line break code to LF
      - id: mixed-line-ending
        args: [--fix=lf]
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml

  # https://github.com/shellcheck-py/shellcheck-py?tab=readme-ov-file#usage
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    # Cannot be executed with local designation (as of 24.8.3)
    rev: 2.3.1
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true

  #- repo: local
  #  hooks:
  #    - id: poetry-export
  #      name: Export requirements.txt
  #      entry: poetry export -f requirements.txt -o requirements.txt --without-hashes
  #      language: python
  #      pass_filenames: false
  #      additional_dependencies:
  #        - "poetry"
  #        - "poetry-plugin-export"
  #    - id: poetry-export-dev
  #      name: Export dev requirements.txt
  #      entry: poetry export --with dev -f requirements.txt -o requirements-dev.txt --without-hashes
  #      language: python
  #      pass_filenames: false
  #      additional_dependencies:
  #        - "poetry"
  #        - "poetry-plugin-export"

  # Reference: https://github.com/DavidAnson/markdownlint-cli2#overview
  # > markdownlint-cli is a traditional command-line interface for markdownlint.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.json", "README.md"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: ["--fix","repo_dispatch_event_sender"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20240622]
        args: [--config-file=pyproject.toml]
