name: Send Payload Action to Pytest

on:
  push:
    branches:
      - 'main'
    paths:
      - 'repo_dispatch_event_sender/**'
      - 'tests/**'
      - 'poetry.lock'

jobs:
  test-and-send-dispatch:
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !startsWith(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    permissions:
      # Enable code checkout
      contents: write
      # Enable repository_dispatch triggers
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Send Payload to Pytest
        uses: 7rikazhexde/repo-dispatch-event-sender@main
        #uses: ./
        with:
          repository_name: '7rikazhexde/repo-dispatch-event-sender'
          event_type: 'send_payload_to_pytest'
          os_list: '[ubuntu-latest,macos-13,windows-latest]'
          version_list: '[3.10,3.11,3.12,3.13]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Must Allow "Read and write permissions" from Workflow permissions
          #GH_TOKEN: ${{ secrets.PAT_FOR_PUSHES }}
